AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AuditBucket:
    Type: 'AWS::S3::Bucket'
    Properties: {BucketName: organization-audit-logs}
  AuditBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref AuditBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: s3:GetBucketAcl
            Effect: Allow
            Principal: {Service: cloudtrail.amazonaws.com}
            Resource: !GetAtt AuditBucket.Arn
          - Action: s3:PutObject
            Effect: Allow
            Principal: {Service: cloudtrail.amazonaws.com}
            Resource: !Sub '${AuditBucket.Arn}/AWSLogs/*'
            Condition: {StringEquals: {'s3:x-amz-acl': bucket-owner-full-control}}
  GlobalTrail:
    Type: 'AWS::CloudTrail::Trail'
    Properties:
      TrailName: GlobalAuditTrail
      S3BucketName: !Ref AuditBucket
      IsLogging: true
      IsMultiRegionTrail: true
      IncludeGlobalServiceEvents: true
